//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservas.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Page {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Page() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reservas.App_GlobalResources.Page", typeof(Page).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change region.
        /// </summary>
        public static string CHANGE_REGION_TITLE {
            get {
                return ResourceManager.GetString("CHANGE_REGION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your region.
        /// </summary>
        public static string CHOOSE_YOUR_REGION_TITLE {
            get {
                return ResourceManager.GetString("CHOOSE_YOUR_REGION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flights.
        /// </summary>
        public static string FLIGHTS {
            get {
                return ResourceManager.GetString("FLIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search flights.
        /// </summary>
        public static string FLIGHTS_SEARCH {
            get {
                return ResourceManager.GetString("FLIGHTS_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string HOME_TITLE {
            get {
                return ResourceManager.GetString("HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string HOTELS {
            get {
                return ResourceManager.GetString("HOTELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search hotels.
        /// </summary>
        public static string HOTELS_SEARCH {
            get {
                return ResourceManager.GetString("HOTELS_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a region changes the language and/or content.
        /// </summary>
        public static string REGION_SELECTOR_DESC {
            get {
                return ResourceManager.GetString("REGION_SELECTOR_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-city.
        /// </summary>
        public static string SEARCH_FORM__MULTI_CITY {
            get {
                return ResourceManager.GetString("SEARCH_FORM__MULTI_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One way.
        /// </summary>
        public static string SEARCH_FORM__ONE_WAY {
            get {
                return ResourceManager.GetString("SEARCH_FORM__ONE_WAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round trip.
        /// </summary>
        public static string SEARCH_FORM__ROUND_TRIP {
            get {
                return ResourceManager.GetString("SEARCH_FORM__ROUND_TRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special offers from airlines.
        /// </summary>
        public static string SPECIAL_OFFERS_TITLE {
            get {
                return ResourceManager.GetString("SPECIAL_OFFERS_TITLE", resourceCulture);
            }
        }
    }
}
